runtime: nodejs20

env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  # Serve static assets
  - url: /(assets/.*)
    static_files: vite-project/dist/\1
    upload: vite-project/dist/assets/.*

  # Serve root static files
  - url: /(.*\.(js|css|ico|png|json))
    static_files: vite-project/dist/\1
    upload: vite-project/dist/.*\.(js|css|ico|png|json)$

  # All other routes go to index.html
  - url: /.*
    static_files: vite-project/dist/index.html
    upload: vite-project/dist/index.html

env_variables:
  NODE_ENV: "production"
